### PR TITLE
Fix account endpoint address

### PR DESCRIPTION
**Pull request by moodmosaic**
At least that's what seems to be working for me in the .NET SDK.

### CODE REVIEW

**Comment by tdietert** [comment]
I think there is some confusion between _querying_ the state of the ledger, and _submitting_ a valid transaction to the ledger. In this bit of code, defining the`CreateAccount` Response object, the url should indeed be `<ipOfUplinkNode>/`, because this is the endpoint on which the Uplink RPC interface accepts validly encoded representations of well-formed Transactions. 

I think the endpoint url you are confusing this with is the endpoint here: https://github.com/adjoint-io/uplink-sdk-java/blob/master/src/main/java/adjoint/uplink_sdk/client/UplinkSDK.java#L149 with which users can _query_ all accounts on the ledger.

Is there somewhere in the documentation that makes this unclear? If so, please let me know and we'll fix it shorty.

**Comment by moodmosaic** [comment]
I think the documentation around this is pretty clear; perhaps I miss something while trying to `POST` this:

```json
{
   "Method":"Transaction",
   "Params":{
      "Timestamp":1473477224,
      "Signature":"AE02OTc5NjIzMDQwNjkzMTMzMDcwODY1Njc4Mzc1MTc2NDM2MTI5NTQ4OTg3NTM0MzUwNTgyOTIxNjY3NzUzMzczMDA2NTg3MjIwODE0MzoATTg0MzkzNDIxNzY3NzIxMTU4NTY5NTYyMjcyNzgyNzY1ODM2NTQwMDI3MjQ0NTE1ODI2OTY2MTkyMzA0MDI3Mzg4NjQzOTg0NTA4NzI4",
      "FromAddress":"yAqjTvG6iQLvPeMt5kdKqdH5hkJ4wj6kSYnocTiriVw",
      "ToAddress":"yAqjTvG6iQLvPeMt5kdKqdH5hkJ4wj6kSYnocTiriVw",
      "Header":{
         "Tag":"TxContract",
         "Contents":{
            "Tag":"CreateAccount",
            "Contents":{
               "PubKey":"w;c\f©©dõ´p\u0007°n\u0004!ÿ\u000fpsdüòˆrãhý©â`öë›íï×îg«÷\u001eg¡g=\u0002§ôl\u0014ò4\u001d\u0005–6àô4b´f",
               "Timezone":"EST",
               "Meta":[
                  {
                     "Key":"foo",
                     "Value":"1"
                  },
                  {
                     "Key":"bar",
                     "Value":"10"
                  }
               ]
            }
         }
      }
   }
}
```

`POST`ing this to the `ipOfUplinkNode>/` gets back the following error response, which I think doesn't provide much information (https://github.com/adjoint-io/uplink/issues/1):

```json
{
   "tag":"RPCRespError",
   "contents":{
      "errorMsg":"Error in $: not enough input",
      "errorType":"JSONParse"
   }
}
```

**Comment by tdietert** [comment]
I agree, it is a pretty horrible error message. This is we are sending bytestrings as JSON fields, and unfortunately the library we use is returning quite poor error messages. I would suggest a few things though, before I look into this deeper:

1) The json field names (the "key"s) should all be lowercase
2) Anytime you send a bytestring, please encode it as UTF8

Please try these two things and let me know how it goes.

**Comment by dtseng123** [comment]
It looks like your pubKey is encoded incorrectly and make sure the keys are also exactly the same. Here's a well-formed created account example:
`{
  "method": "Transaction",
  "params": {
    "timestamp": 1509107457033000,
    "signature": "AE01NDQ1NjE5MTMxMzg4NjY5MjUyNjIyNDg1NDg3ODY4NTc1NTg4NjQwODIxODAyMjQ2MzkwNjEzNzk1Mjc5MTg4Mzk5NzUwOTE5MDM0ODoATTI4NzA3OTQwMzU3MTI2NjIxOTg5NzY3NDY4NDIxMzM2OTAxOTc2NjAzNjg2MTM4NzUzNDMwOTI2NTg5MTgzNzMxNDI4NTQ5MTYxMDAy",
    "to": "J2Px6tyAKTNHiRBY9WNPRz6Ck6CCPQ1tMbekiy9FG9ec",
    "origin": "J2Px6tyAKTNHiRBY9WNPRz6Ck6CCPQ1tMbekiy9FG9ec",
    "header": {
      "tag": "TxAccount",
      "contents": {
        "tag": "CreateAccount",
        "contents": {
          "pubKey": "23f319b2f15dab590c9238bdd0b407d9cb748d6f9052addbef3647764882641b41ffd806473869750d5006c15026c581115683bd80e46387503ad1b26fc0cac4",
          "timezone": "EST",
          "metadata": {
            "a": "z",
            "foo": "bar",
            "shake": "bake"
          }
        }
      }
    }
  }
}`

**Comment by moodmosaic** [comment]
@tdietert 
>Assuming you are sending this JSON body from the .NET SDK

That's correct. (And I'll make sure to point it out--or open issues on the .NET SDK in the future. I apologize for this!)

@dtseng123 
Thank you! I think I'm very close now 🎉

**Pull request closed without merging**
